version: '2'

services:
  front-end:
    image: continuityproject/sock-shop-front-end:latest
    hostname: front-end
    command: nodemon -L --inspect=0.0.0.0:8888 /usr/src/app/server.js
    environment:
      - ZIPKIN_PORT=8182
      - ZIPKIN_HOST=cmr
    restart: always
    cap_drop:
      - all
    read_only: true
    ports:
     - '8888:8888'
    links:
          - "cmr:cmr"
  cmr:
    image: continuityproject/inspectit-cmr:latest
    hostname: cmr
    restart: always
    ports:
     - '8182:8182'
     - '9070:9070'

  edge-router:
    image: weaveworksdemos/edge-router
    ports:
      - '80:80'
      - '8080:8080'
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
    tmpfs:
      - /var/run:rw,noexec,nosuid
    hostname: edge-router
    restart: always
  catalogue:
    image: weaveworksdemos/catalogue
    environment:
      - ZIPKIN=http://cmr:8182/rest/api/v1/spans
    hostname: catalogue
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    links:
          - "cmr:cmr"
  catalogue-db:
    image: weaveworksdemos/catalogue-db
    hostname: catalogue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=socksdb
  carts:
    image: weaveworksdemos/carts
    hostname: carts
    restart: always
    volumes:
      - ./:/agent
      - ./script:/script
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=weaveworksdemos-carts -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom

    depends_on:
      - cmr
    entrypoint: ["/script/wait-for","cmr:9070","--timeout=60","--","/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]

  carts-db:
    image: mongo
    hostname: carts-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  orders:
    image: weaveworksdemos/orders
    hostname: orders
    restart: always
    volumes:
      - ./:/agent
      - ./script:/script
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=weaveworksdemos-orders -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    depends_on:
      - cmr
    entrypoint: ["/script/wait-for","cmr:9070","--timeout=60","--","/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]

  orders-db:
    image: mongo
    hostname: orders-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  shipping:
    image: weaveworksdemos/shipping
    hostname: shipping
    restart: always
    volumes:
      - ./:/agent
      - ./script:/script
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xbootclasspath/p:/agent/inspectit-agent.jar -javaagent:/agent/inspectit-agent.jar -Dinspectit.repository=cmr:9070 -Dinspectit.agent.name=weaveworksdemos-shipping -Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
    depends_on:
      - cmr
    entrypoint: ["/script/wait-for","cmr:9070","--timeout=60","--","/usr/local/bin/java.sh","-jar","./app.jar", "--port=80"]
  queue-master:
    image: weaveworksdemos/queue-master
    hostname: queue-master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
  rabbitmq:
    image: rabbitmq:3.6.8
    hostname: rabbitmq
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    read_only: true
  payment:
    image: weaveworksdemos/payment
    environment:
      - ZIPKIN=http://cmr:8182/rest/api/v1/spans
    hostname: payment
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    links:
          - "cmr:cmr"
  user:
    image: weaveworksdemos/user
    environment:
      - ZIPKIN=http://cmr:8182/rest/api/v1/spans
      - MONGO_HOST=user-db:27017
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    links:
          - "cmr:cmr"
  user-db:
    image: weaveworksdemos/user-db
    hostname: user-db
    restart: always
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
